/* SAD HOURS VINYL CLUB — ecommerce logic. Stripe/Netlify checkout kept intact. */

const products = [
  { id: 1, name: "CUSTOM WINDSHIELD BANNER", category: "Window Banners", basePrice: 70, image: "assets/products/windshield-banner.svg", description: "Custom front or rear windshield banner with your wording, club name, brand, or handle. Clean cut, bold presence, car-show ready.", specs: "Cut vinyl • transfer tape included • custom sizing • install guidance included", sizes: ["Small banner", "Standard windshield", "Large / 4x4", "Custom size"], finishes: ["Gloss White", "Matte Black", "Pearl Holographic", "Chrome Silver"], colors: ["White", "Black", "Pearl Holo", "Custom"] },
  { id: 2, name: "CUSTOM DECAL DESIGN", category: "Custom Work", basePrice: 35, image: "assets/products/custom-decal.svg", description: "Send a sketch, logo, screenshot or idea. We clean it up into a vinyl-friendly design that can actually be cut and weeded.", specs: "Design cleanup • vector prep • proof before cut • good for cars, glass and laptops", sizes: ["Small", "Medium", "Large", "Quote custom"], finishes: ["Single Colour", "Two Layer", "Pearl Holographic", "Reflective"], colors: ["White", "Black", "Pearl Holo", "Custom"] },
  { id: 3, name: "PEARL HOLOGRAPHIC DECAL", category: "Car Decals", basePrice: 28, image: "assets/products/pearl-holo.svg", description: "Pearl holographic vinyl decal with a clean high-contrast finish. Built for people who want the shine without cheap rainbow chaos.", specs: "Pearl holo finish • weather resistant • pre-masked • install ready", sizes: ["Small (100mm)", "Medium (200mm)", "Large (300mm)", "XL (450mm)"], finishes: ["Pearl Holographic", "Chrome Holo", "Gloss White", "Gloss Black"], colors: ["Pearl", "Silver", "White", "Black"] },
  { id: 4, name: "BUSINESS WINDOW SIGNAGE", category: "Business Signage", basePrice: 120, image: "assets/products/business-signage.svg", description: "Professional shopfront, ute, trailer, or window lettering for small businesses that need to look sharp fast.", specs: "Custom quote • exterior vinyl • business-ready layout • supplied with transfer tape", sizes: ["Door set", "Shop window", "Trailer / ute", "Quote custom"], finishes: ["Gloss White", "Matte Black", "Two Colour", "Holographic Accent"], colors: ["White", "Black", "Black + White", "Custom"] },
  { id: 5, name: "SAD HOURS STICKER PACK", category: "Sticker Packs", basePrice: 18, image: "assets/products/sticker-pack.svg", description: "A pack of Sad Hours style decals for toolboxes, laptops, cars, water bottles and whatever else needs attitude.", specs: "Multi-pack • outdoor vinyl • mixed mini decals • limited drops", sizes: ["Mini pack", "Standard pack", "Large pack"], finishes: ["Black / White", "Pearl Holo Mix", "Mystery Pack"], colors: ["Mixed", "Black White", "Pearl"] },
  { id: 6, name: "LAYERED VINYL GRAPHIC", category: "Custom Work", basePrice: 55, image: "assets/products/layered-vinyl.svg", description: "Two or three colour layered vinyl graphics prepared with clean separations so you can get that multi-colour look properly.", specs: "Layer separation • registration-friendly • cut-safe lines • quote depends on size", sizes: ["Small", "Medium", "Large", "Quote custom"], finishes: ["2 Layer", "3 Layer", "Holographic Accent"], colors: ["Black + White", "Black + Red", "Black + Holo", "Custom"] },
  { id: 7, name: "INSTAGRAM HANDLE DECAL", category: "Car Decals", basePrice: 22, image: "assets/products/instagram-handle.svg", description: "Clean social handle decal with icon. Perfect for rear quarter windows, business cars, trailers and promo builds.", specs: "Custom handle • icon included • small business friendly • clean cut", sizes: ["200mm", "300mm", "500mm", "Custom"], finishes: ["Gloss White", "Matte Black", "Pearl Holo", "Chrome"], colors: ["White", "Black", "Pearl", "Custom"] },
  { id: 8, name: "SAD HOURS LOGO DECAL", category: "Sticker Packs", basePrice: 25, image: "assets/logo-transparent.png", description: "The official Sad Hours Vinyl Club logo decal. Black and white street-style branding with the sad girl artwork.", specs: "Logo decal • high contrast • clean vinyl look • limited brand piece", sizes: ["Small", "Medium", "Large", "XL"], finishes: ["Black / White", "Pearl Holo Accent", "Gloss White"], colors: ["Black White", "Pearl", "White"] }
];

let cart = [];
let currentProduct = null;
let currentFilters = { category: 'All', search: '', sort: 'featured' };

function formatPrice(price) { return '$' + price.toFixed(0); }
function showToast(message, type = 'success') {
  const container = document.getElementById('toast-container'); if (!container) return;
  const toast = document.createElement('div');
  toast.className = `toast flex items-center gap-3 px-5 py-4 rounded-2xl shadow-2xl max-w-xs ${type === 'success' ? 'bg-[#080809] border border-white/15 text-white' : 'bg-red-950 border border-red-900 text-red-100'}`;
  toast.innerHTML = `<div class="flex-1 text-sm font-bold">${message}</div><button class="text-white/50 hover:text-white" onclick="this.parentElement.remove()">✕</button>`;
  container.appendChild(toast);
  setTimeout(() => { if (toast.parentNode) toast.parentNode.removeChild(toast); }, 3400);
}
function saveCart() { localStorage.setItem('shvc_cart', JSON.stringify(cart)); updateCartCount(); }
function loadCart() { const saved = localStorage.getItem('shvc_cart'); if (saved) cart = JSON.parse(saved); updateCartCount(); }
function updateCartCount() { const countEl = document.getElementById('cart-count'); if (!countEl) return; const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0); countEl.textContent = totalItems; countEl.classList.toggle('hidden', totalItems === 0); }

function getFilteredProducts() {
  let result = [...products];
  if (currentFilters.category !== 'All') result = result.filter(p => p.category === currentFilters.category);
  if (currentFilters.search) { const term = currentFilters.search.toLowerCase(); result = result.filter(p => p.name.toLowerCase().includes(term) || p.description.toLowerCase().includes(term) || p.category.toLowerCase().includes(term)); }
  switch (currentFilters.sort) { case 'price-low': result.sort((a,b)=>a.basePrice-b.basePrice); break; case 'price-high': result.sort((a,b)=>b.basePrice-a.basePrice); break; case 'name': result.sort((a,b)=>a.name.localeCompare(b.name)); break; }
  return result;
}
function renderProducts() {
  const grid = document.getElementById('product-grid'); if (!grid) return;
  const filtered = getFilteredProducts();
  if (!filtered.length) { grid.innerHTML = `<div class="col-span-full py-12 text-center"><p class="text-white/55">No vinyl found for that search.</p><button onclick="resetFilters()" class="btn btn-secondary mt-4 px-6 py-3">Clear Filters</button></div>`; return; }
  grid.innerHTML = filtered.map(product => `
    <div class="product-card rounded-2xl overflow-hidden group cursor-pointer" onclick="openProductModal(${product.id})">
      <div class="image-container aspect-square relative"><img src="${product.image}" alt="${product.name}" class="w-full h-full object-cover"><div class="absolute top-3 right-3 px-3 py-1 text-[10px] font-black tracking-[1px] bg-black/75 border border-white/15 text-white rounded-full">${product.category.toUpperCase()}</div></div>
      <div class="p-5"><div class="font-black text-lg tracking-tight mb-1">${product.name}</div><div class="text-sm text-white/50 mb-4 line-clamp-2">${product.description.substring(0, 96)}...</div><div class="flex items-center justify-between gap-3"><div><span class="text-xl font-black tracking-tighter">${formatPrice(product.basePrice)}</span><span class="text-xs text-white/45"> from</span></div><button onclick="event.stopImmediatePropagation(); quickAddToCart(${product.id})" class="btn btn-primary text-xs px-4 py-2">ADD</button></div></div>
    </div>`).join('');
}
function resetFilters() { currentFilters = { category:'All', search:'', sort:'featured' }; document.getElementById('search-input').value=''; document.querySelectorAll('.filter-pill').forEach(p=>p.classList.remove('active')); document.querySelector('.filter-pill[data-category="All"]').classList.add('active'); document.getElementById('sort-select').value='featured'; renderProducts(); }

function openProductModal(productId) {
  currentProduct = products.find(p => p.id === productId); if (!currentProduct) return;
  const modal = document.getElementById('product-modal'); const content = document.getElementById('product-modal-content');
  content.innerHTML = `<div class="grid md:grid-cols-2 gap-8"><div class="bg-[#050506] rounded-2xl overflow-hidden aspect-square border border-white/10"><img src="${currentProduct.image}" alt="${currentProduct.name}" class="w-full h-full object-cover"></div><div class="flex flex-col"><div class="flex justify-between items-start mb-2"><div><div class="uppercase tracking-[2px] text-xs text-white/45 mb-1 font-black">${currentProduct.category}</div><h3 class="text-3xl font-black tracking-tighter">${currentProduct.name}</h3></div><button onclick="closeProductModal()" class="text-3xl text-white/50 hover:text-white leading-none mt-1">&times;</button></div><div class="text-3xl font-black tracking-[-1.5px] mt-2 mb-6">${formatPrice(currentProduct.basePrice)} <span class="text-base font-normal text-white/45">starting</span></div><p class="text-white/65 leading-relaxed">${currentProduct.description}</p><div class="my-6 text-xs text-white/50 font-black tracking-widest border-l-2 border-white/50 pl-4">${currentProduct.specs}</div><div class="space-y-6 mt-auto pt-4"><div><div class="text-xs font-black tracking-widest text-white/45 mb-2">SIZE</div><div class="flex flex-wrap gap-2" id="size-options">${currentProduct.sizes.map((size,i)=>`<button class="option-btn ${i===0?'active':''}" data-value="${size}" onclick="selectOption(this, 'size')">${size}</button>`).join('')}</div></div><div><div class="text-xs font-black tracking-widest text-white/45 mb-2">FINISH</div><div class="flex flex-wrap gap-2" id="finish-options">${currentProduct.finishes.map((finish,i)=>`<button class="option-btn ${i===0?'active':''}" data-value="${finish}" onclick="selectOption(this, 'finish')">${finish}</button>`).join('')}</div></div><div><div class="text-xs font-black tracking-widest text-white/45 mb-2">COLOUR / VARIANT</div><div class="flex flex-wrap gap-2" id="color-options">${currentProduct.colors.map((color,i)=>`<button class="option-btn ${i===0?'active':''}" data-value="${color}" onclick="selectOption(this, 'color')">${color}</button>`).join('')}</div></div><div><div class="text-xs font-black tracking-widest text-white/45 mb-2">QUANTITY</div><div class="flex items-center gap-4"><div class="flex border border-white/15 rounded-xl"><button onclick="changeQuantity(-1)" class="px-4 py-2 text-xl hover:bg-white/10">-</button><div id="modal-qty" class="px-6 py-2 font-mono border-x border-white/15">1</div><button onclick="changeQuantity(1)" class="px-4 py-2 text-xl hover:bg-white/10">+</button></div><div id="line-total" class="text-xl font-black tracking-tight">${formatPrice(currentProduct.basePrice)}</div></div></div></div><div class="flex gap-3 mt-8"><button onclick="addCurrentProductToCart()" class="btn btn-primary flex-1 text-sm py-3.5">ADD TO CART</button><button onclick="closeProductModal()" class="btn btn-secondary flex-1 text-sm py-3.5">MAYBE LATER</button></div></div></div>`;
  window.selectedOptions = { size: currentProduct.sizes[0], finish: currentProduct.finishes[0], color: currentProduct.colors[0], quantity: 1 };
  modal.classList.remove('hidden'); modal.classList.add('flex');
}
function selectOption(btn, type) { btn.parentElement.querySelectorAll('.option-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); window.selectedOptions[type] = btn.dataset.value; updateModalPrice(); }
function changeQuantity(delta) { const qtyEl=document.getElementById('modal-qty'); let qty=parseInt(qtyEl.textContent)+delta; if(qty<1) qty=1; qtyEl.textContent=qty; window.selectedOptions.quantity=qty; updateModalPrice(); }
function updateModalPrice() { if(!currentProduct||!window.selectedOptions) return; const qty=window.selectedOptions.quantity||1; let multiplier=1; if(qty>=5) multiplier=.88; else if(qty>=3) multiplier=.93; const total=Math.round(currentProduct.basePrice*multiplier*qty); const el=document.getElementById('line-total'); if(el) el.innerHTML=formatPrice(total); }
function closeProductModal() { const modal=document.getElementById('product-modal'); modal.classList.remove('flex'); modal.classList.add('hidden'); currentProduct=null; }
function addCurrentProductToCart() { if(!currentProduct||!window.selectedOptions) return; const opts=window.selectedOptions; const qty=opts.quantity||1; let multiplier=1; if(qty>=5) multiplier=.88; else if(qty>=3) multiplier=.93; const unitPrice=Math.round(currentProduct.basePrice*multiplier); cart.push({ id: Date.now(), productId: currentProduct.id, name: currentProduct.name, size: opts.size, finish: opts.finish, color: opts.color, quantity: qty, unitPrice }); const name=currentProduct.name; saveCart(); closeProductModal(); showToast(`Added ${qty}× ${name}`); openCartDrawer(); }
function quickAddToCart(productId) { const product=products.find(p=>p.id===productId); if(!product) return; cart.push({ id: Date.now(), productId: product.id, name: product.name, size: product.sizes[0], finish: product.finishes[0], color: product.colors[0], quantity: 1, unitPrice: product.basePrice }); saveCart(); showToast(`Added ${product.name}`); }

function openCartDrawer() {
  const drawer=document.getElementById('cart-drawer'); const content=document.getElementById('cart-content');
  if(cart.length===0) content.innerHTML=`<div class="flex flex-col items-center justify-center h-full text-center px-6"><div class="text-6xl mb-6 opacity-30">✦</div><div class="font-black text-xl mb-2">Your cart is empty</div><p class="text-white/50 max-w-xs">Time to put some Sad Hours vinyl on something.</p><button onclick="closeCartDrawer(); document.getElementById('shop').scrollIntoView({behavior:'smooth'})" class="btn btn-primary mt-8 px-6 py-3">BROWSE DECALS</button></div>`;
  else { let subtotal=0; const itemsHTML=cart.map((item,index)=>{ const lineTotal=item.unitPrice*item.quantity; subtotal+=lineTotal; return `<div class="flex gap-4 py-5 border-b border-white/10"><div class="flex-1"><div class="font-black tracking-tight">${item.name}</div><div class="text-xs text-white/45 mt-1">${item.size} • ${item.finish} • ${item.color}</div><div class="flex items-center gap-4 mt-3"><div class="flex items-center border border-white/15 text-xs rounded-xl"><button onclick="adjustCartItem(${index}, -1)" class="px-3 py-1 hover:bg-white/10">-</button><span class="px-3 py-1 font-mono border-x border-white/15">${item.quantity}</span><button onclick="adjustCartItem(${index}, 1)" class="px-3 py-1 hover:bg-white/10">+</button></div><button onclick="removeFromCart(${index})" class="text-xs text-white/45 hover:text-red-300">REMOVE</button></div></div><div class="text-right font-black tabular-nums">${formatPrice(lineTotal)}</div></div>`; }).join(''); content.innerHTML=`<div class="flex-1 overflow-auto pr-1">${itemsHTML}</div><div class="pt-5 border-t border-white/10 mt-auto"><div class="flex justify-between text-sm mb-2"><span class="text-white/45">SUBTOTAL</span><span class="font-black">${formatPrice(subtotal)}</span></div><div class="flex justify-between text-xs text-white/45 mb-6"><span>Shipping</span><span>Calculated at checkout</span></div><button onclick="proceedToCheckout()" class="btn btn-primary w-full py-3.5 text-sm tracking-wider">PROCEED TO CHECKOUT</button><button onclick="closeCartDrawer()" class="btn btn-ghost w-full mt-2 text-xs py-3">CONTINUE BROWSING</button></div>`; }
  drawer.classList.remove('hidden'); drawer.classList.add('flex');
}
function closeCartDrawer(){ const drawer=document.getElementById('cart-drawer'); drawer.classList.remove('flex'); drawer.classList.add('hidden'); }
function adjustCartItem(index,delta){ cart[index].quantity+=delta; if(cart[index].quantity<1) cart[index].quantity=1; saveCart(); openCartDrawer(); }
function removeFromCart(index){ cart.splice(index,1); saveCart(); openCartDrawer(); }

function showLoadingOverlay(message='Connecting to secure checkout...') { const existing=document.getElementById('loading-overlay'); if(existing) existing.remove(); const overlay=document.createElement('div'); overlay.id='loading-overlay'; overlay.className='fixed inset-0 z-[200] bg-black/95 flex items-center justify-center'; overlay.innerHTML=`<div class="text-center px-6"><div class="mx-auto mb-6 h-9 w-9 animate-spin rounded-full border-[3px] border-white border-t-transparent"></div><div class="text-base md:text-lg font-black tracking-[-0.3px]">${message}</div><div class="mt-2 text-xs text-white/45 tracking-wider">SECURE CHECKOUT POWERED BY STRIPE</div></div>`; document.body.appendChild(overlay); }
function hideLoadingOverlay(){ const overlay=document.getElementById('loading-overlay'); if(overlay) overlay.remove(); }

async function proceedToCheckout() {
  closeCartDrawer();
  const modal=document.createElement('div'); modal.className='fixed inset-0 z-[130] bg-black/90 flex items-center justify-center p-4';
  let subtotal=0; cart.forEach(item=>subtotal+=item.unitPrice*item.quantity); const shipping=subtotal>120?0:12; const total=subtotal+shipping;
  const summaryHTML=cart.map(item=>`<div class="flex justify-between text-sm py-2 border-b border-white/10"><div><div class="font-bold">${item.name}</div><div class="text-[11px] text-white/45">${item.size} • ${item.finish} • ${item.color}</div></div><div class="text-right"><div>${item.quantity}× ${formatPrice(item.unitPrice)}</div><div class="text-xs text-white/45">${formatPrice(item.unitPrice*item.quantity)}</div></div></div>`).join('');
  modal.innerHTML=`<div class="modal bg-[#080809] border border-white/15 w-full max-w-lg rounded-2xl overflow-hidden max-h-[94vh] md:max-h-[92vh] overflow-y-auto"><div class="px-6 py-5 border-b border-white/10 flex justify-between items-center"><div class="font-black tracking-wide">REVIEW YOUR ORDER</div><button id="pre-cancel" class="text-2xl text-white/50 hover:text-white leading-none">&times;</button></div><div class="p-5 md:p-6"><div class="mb-5 md:mb-6"><div class="text-xs uppercase tracking-[1.5px] text-white/45 mb-2 md:mb-3 font-black">YOUR VINYL</div><div class="max-h-[180px] md:max-h-[220px] overflow-auto pr-1 space-y-1 text-sm">${summaryHTML}</div></div><div class="border-t border-white/10 pt-4 space-y-1 text-sm mb-6"><div class="flex justify-between"><span class="text-white/45">Subtotal</span><span>${formatPrice(subtotal)}</span></div><div class="flex justify-between"><span class="text-white/45">Shipping</span><span>${shipping===0?'FREE':formatPrice(shipping)}</span></div><div class="flex justify-between pt-2 border-t border-white/10 font-black text-base"><span>Total</span><span>${formatPrice(total)}</span></div></div><div><div class="text-xs uppercase tracking-[1.5px] text-white/45 mb-3 font-black">YOUR INFORMATION</div><div class="space-y-3"><input id="pre-name" type="text" placeholder="FULL NAME" class="input w-full" /><input id="pre-email" type="email" placeholder="EMAIL ADDRESS" class="input w-full" /></div></div></div><div class="px-6 py-5 border-t border-white/10 bg-white/[.025]"><button id="pre-continue" class="btn btn-primary w-full py-3.5 text-sm">CONTINUE TO SECURE PAYMENT →</button><div class="flex items-center justify-between mt-4 text-xs"><button id="pre-edit-cart" class="text-white/45 hover:text-white underline underline-offset-2">Edit Cart</button><div class="text-white/35 tracking-widest">POWERED BY STRIPE</div></div></div></div>`;
  document.body.appendChild(modal); setTimeout(()=>document.getElementById('pre-name')?.focus(),200);
  document.getElementById('pre-cancel').onclick=()=>modal.remove(); document.getElementById('pre-edit-cart').onclick=()=>{ modal.remove(); setTimeout(openCartDrawer,180); };
  document.getElementById('pre-continue').onclick=async()=>{ const name=document.getElementById('pre-name').value.trim()||'Customer'; const email=document.getElementById('pre-email').value.trim(); if(!email||!email.includes('@')){ alert('Please enter a valid email address.'); return; } modal.remove(); showLoadingOverlay('Connecting to Stripe...'); try { const response=await fetch('/.netlify/functions/create-checkout-session',{ method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({cart, customerEmail:email, customerName:name}) }); const data=await response.json(); if(data.url) setTimeout(()=>{ window.location.href=data.url; },450); else { hideLoadingOverlay(); throw new Error(data.error||'Failed to start checkout'); } } catch(error) { hideLoadingOverlay(); console.error('[Sad Hours] Checkout error:',error); const errorMessage=error?.message||'Something went wrong starting checkout.'; showToast(errorMessage,'error'); if(errorMessage.length>60) alert(errorMessage); } };
}

function openCustomModal(){ const modal=document.getElementById('custom-modal'); modal.classList.remove('hidden'); modal.classList.add('flex'); }
function closeCustomModal(){ const modal=document.getElementById('custom-modal'); modal.classList.remove('flex'); modal.classList.add('hidden'); }
function submitCustomOrder(e){ e.preventDefault(); const form=e.target; const name=form.querySelector('#custom-name').value; closeCustomModal(); setTimeout(()=>{ const modal=document.getElementById('success-modal'); modal.classList.remove('hidden'); modal.classList.add('flex'); modal.innerHTML=`<div class="modal bg-[#080809] border border-white/15 max-w-md w-full mx-4 rounded-2xl p-8 text-center"><div class="holo-text text-5xl mb-4">✓</div><h3 class="text-2xl font-black tracking-tight mb-3">REQUEST RECEIVED</h3><p class="text-white/65">Thanks, ${name.split(' ')[0]}. We’ll review the project and send back a proof or quote.</p><button onclick="closeSuccessModal()" class="btn btn-primary mt-8 w-full py-3">GOT IT</button></div>`; form.reset(); },250); }
function closeSuccessModal(){ document.getElementById('success-modal').classList.add('hidden'); document.getElementById('success-modal').classList.remove('flex'); }

function setupFilters(){ document.querySelectorAll('.filter-pill').forEach(pill=>pill.addEventListener('click',()=>{ document.querySelectorAll('.filter-pill').forEach(p=>p.classList.remove('active')); pill.classList.add('active'); currentFilters.category=pill.dataset.category; renderProducts(); })); const search=document.getElementById('search-input'); if(search) search.addEventListener('input',()=>{ currentFilters.search=search.value; renderProducts(); }); document.getElementById('sort-select')?.addEventListener('change',e=>{ currentFilters.sort=e.target.value; renderProducts(); }); }
function setupMobileNav(){ const toggle=document.getElementById('mobile-nav-toggle'); const nav=document.getElementById('mobile-nav'); if(!toggle||!nav) return; toggle.addEventListener('click',()=>{ nav.classList.toggle('open'); nav.classList.toggle('hidden'); }); nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{ nav.classList.remove('open'); nav.classList.add('hidden'); })); }
function setupFAQ(){ document.querySelectorAll('.faq-question').forEach(q=>q.addEventListener('click',()=>{ const answer=q.nextElementSibling; const isOpen=answer.classList.contains('open'); document.querySelectorAll('.faq-answer').forEach(a=>a.classList.remove('open')); if(!isOpen) answer.classList.add('open'); })); }
function handlePaymentReturnState(){ const params=new URLSearchParams(window.location.search); if(params.get('payment')==='cancelled'){ setTimeout(()=>showToast('Payment cancelled. Your cart is still saved.','error'),600); const cleanUrl=window.location.pathname+window.location.hash; window.history.replaceState({},document.title,cleanUrl); } }
function initialize(){ loadCart(); renderProducts(); setupFilters(); setupMobileNav(); setupFAQ(); handlePaymentReturnState(); document.addEventListener('keydown',e=>{ if(e.key==='Escape'){ ['product-modal','cart-drawer','custom-modal','success-modal'].forEach(id=>{ const m=document.getElementById(id); if(m){ m.classList.remove('flex'); m.classList.add('hidden'); } }); } }); console.log('%c[Sad Hours Vinyl Club] rebrand loaded.', 'color:#fff;background:#000'); }
document.addEventListener('DOMContentLoaded', initialize);
